<a href="https://colab.research.google.com/github/lumosityfan/NeuralNetworkProject/blob/main/Project_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project #3
By: Jeff Xie

This section imports the make_classification method and creates the input dataset to be used by the neural networks.

In [ ]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=200, n_features=12)

print("Input array: ", X)
print("Size of input array: ", len(X))
print("Number of input nodes: ", len(X[0]))

Input array:  [[ 1.25213229 -1.2716488   0.82113324 ... -0.07053073 -0.38026771
  -2.16851431]
 [-0.75038481  2.1563179  -1.82991319 ... -0.66206991  0.42540449
  -2.41667276]
 [ 0.19430217  0.47575661  0.27047338 ... -0.6110389   0.03634455
   0.99750546]
 ...
 [ 1.4716253  -1.22861591  0.58304491 ... -0.4824417  -0.40925132
   0.7310665 ]
 [-1.50797234  0.75010732 -1.33661898 ... -0.06215807  0.34727215
   0.78526833]
 [ 1.5420235  -1.80896521  0.29817831 ... -0.9786367  -0.5027181
  -0.34867511]]
Size of input array:  200
Number of input nodes:  12


This section imports the necessary tensorflow packages and creates the full neural network.

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Full neural network
full_model = keras.models.Sequential([layers.Dense(8, activation="sigmoid", input_shape=(12,)),
                                      layers.Dense(4, activation="sigmoid"),
                                      layers.Dense(8, activation="sigmoid"),
                                      layers.Dense(12, activation="sigmoid")])
full_output = full_model(X)
print(full_output)

tf.Tensor(
[[0.6074105  0.6614582  0.4638577  ... 0.5337326  0.65061975 0.5349616 ]
 [0.6083948  0.6626919  0.46262714 ... 0.53461057 0.65125394 0.5337588 ]
 [0.6027504  0.6654543  0.46446237 ... 0.5302997  0.65000683 0.52887934]
 ...
 [0.60238373 0.6625101  0.46204326 ... 0.53064793 0.64814615 0.52715653]
 [0.60342866 0.6638775  0.45957556 ... 0.5306764  0.6481276  0.5237668 ]
 [0.605551   0.66285837 0.46583515 ... 0.53368926 0.65131646 0.5357676 ]], shape=(200, 12), dtype=float32)


This section creates the first-half neural network.

In [ ]:
# First-half neural network
first_half = keras.models.Sequential([layers.Dense(8, activation="sigmoid", input_shape=(12,)),
                                      layers.Dense(4, activation="sigmoid")])
fhalf_output = first_half(X)
print(fhalf_output)

tf.Tensor(
[[0.36092457 0.2671855  0.36983714 0.6506922 ]
 [0.23548107 0.2905538  0.44252834 0.52507913]
 [0.4438927  0.25694245 0.39746767 0.6093987 ]
 [0.38752776 0.3679893  0.47087416 0.44317847]
 [0.26868162 0.311839   0.53360444 0.44779104]
 [0.472644   0.26320735 0.35684177 0.6295077 ]
 [0.2984261  0.29979914 0.42136416 0.4696634 ]
 [0.37222    0.32274404 0.41804597 0.5538677 ]
 [0.37807116 0.36111277 0.4372973  0.4993588 ]
 [0.38566315 0.37524924 0.430349   0.45863816]
 [0.31323662 0.36877578 0.5062943  0.4693766 ]
 [0.44754824 0.33120534 0.39208046 0.5564074 ]
 [0.31305906 0.34856305 0.4486863  0.50669926]
 [0.27512372 0.29708618 0.40296674 0.48742732]
 [0.38204283 0.35372376 0.44944954 0.5364378 ]
 [0.46831742 0.41303718 0.46525466 0.530661  ]
 [0.34604967 0.4369839  0.5389676  0.46891972]
 [0.35125613 0.3940778  0.46240047 0.39747557]
 [0.27852643 0.30815765 0.49196884 0.51144356]
 [0.4644978  0.3558912  0.46237525 0.5648852 ]
 [0.31297112 0.30637068 0.45447403 0.5240584 ]
 [

This section creates the second-half neural network.

In [ ]:
# Second-half neural network
second_half = keras.models.Sequential([layers.Dense(8, activation="sigmoid", input_shape=(4,)),
                                       layers.Dense(12, activation="sigmoid")])
shalf_output = second_half(fhalf_output)
print(shalf_output)

tf.Tensor(
[[0.42026824 0.4059714  0.39739594 ... 0.36888954 0.5969662  0.35154036]
 [0.421324   0.4040182  0.39923814 ... 0.36589423 0.5989993  0.35342816]
 [0.4190604  0.40622538 0.39848667 ... 0.36651888 0.5962443  0.35326636]
 ...
 [0.42070174 0.4051504  0.39897653 ... 0.36442038 0.59336895 0.35762236]
 [0.42247874 0.403665   0.3999191  ... 0.36287943 0.59674966 0.35702908]
 [0.42041698 0.40563437 0.39811966 ... 0.36621183 0.59245646 0.3569418 ]], shape=(200, 12), dtype=float32)


This section calculates the error for each node of the full neural network and then calculates the full error of the nodes for the full neural network.

In [ ]:
# Check error for full neural network
full_error = [None] * len(X)
total_full_error = 0;
for i in range(0, len(X)):
  error = 0
  for j in range(0, len(X[0])):
    error += 0.5*pow(X[i][j] - full_output[i][j], 2)
  full_error[i] = error
  total_full_error += error
  print("Error of node ", i, ": ", full_error[i])
print("Total full error of nodes: ", total_full_error)

Error of node  0 :  tf.Tensor(10.534409, shape=(), dtype=float32)
Error of node  1 :  tf.Tensor(12.781321, shape=(), dtype=float32)
Error of node  2 :  tf.Tensor(3.5108128, shape=(), dtype=float32)
Error of node  3 :  tf.Tensor(10.771546, shape=(), dtype=float32)
Error of node  4 :  tf.Tensor(13.327218, shape=(), dtype=float32)
Error of node  5 :  tf.Tensor(6.16209, shape=(), dtype=float32)
Error of node  6 :  tf.Tensor(6.215895, shape=(), dtype=float32)
Error of node  7 :  tf.Tensor(5.998143, shape=(), dtype=float32)
Error of node  8 :  tf.Tensor(9.012973, shape=(), dtype=float32)
Error of node  9 :  tf.Tensor(14.673884, shape=(), dtype=float32)
Error of node  10 :  tf.Tensor(6.144673, shape=(), dtype=float32)
Error of node  11 :  tf.Tensor(5.3476377, shape=(), dtype=float32)
Error of node  12 :  tf.Tensor(8.853355, shape=(), dtype=float32)
Error of node  13 :  tf.Tensor(9.728066, shape=(), dtype=float32)
Error of node  14 :  tf.Tensor(4.3806205, shape=(), dtype=float32)
Error of node

This section calculates the error for each node of the 2 halves of the neural network and then calculates the total halves error of the nodes.

In [ ]:
# Check error for two halves of the neural network
halves_error = [None] * len(X)
total_halves_error = 0
for i in range(0, len(X)):
  error = 0
  for j in range(0, len(X[0])):
    error += 0.5*pow(X[i][j] - shalf_output[i][j], 2)
  halves_error[i] = error
  total_halves_error += error
  print("Error of node ", i, ": ", halves_error[i])
print("Total halves error of nodes: ", total_halves_error)

Error of node  0 :  tf.Tensor(9.328076, shape=(), dtype=float32)
Error of node  1 :  tf.Tensor(12.032896, shape=(), dtype=float32)
Error of node  2 :  tf.Tensor(3.0781143, shape=(), dtype=float32)
Error of node  3 :  tf.Tensor(10.593229, shape=(), dtype=float32)
Error of node  4 :  tf.Tensor(12.804226, shape=(), dtype=float32)
Error of node  5 :  tf.Tensor(5.3763328, shape=(), dtype=float32)
Error of node  6 :  tf.Tensor(6.206714, shape=(), dtype=float32)
Error of node  7 :  tf.Tensor(5.4565387, shape=(), dtype=float32)
Error of node  8 :  tf.Tensor(8.143305, shape=(), dtype=float32)
Error of node  9 :  tf.Tensor(14.018849, shape=(), dtype=float32)
Error of node  10 :  tf.Tensor(5.6297145, shape=(), dtype=float32)
Error of node  11 :  tf.Tensor(4.7926373, shape=(), dtype=float32)
Error of node  12 :  tf.Tensor(8.059116, shape=(), dtype=float32)
Error of node  13 :  tf.Tensor(9.082657, shape=(), dtype=float32)
Error of node  14 :  tf.Tensor(3.7868109, shape=(), dtype=float32)
Error of n